- name: Search API - Pull image
  community.docker.docker_image:
    name: '{{ ghcr_registry }}/{{ app_name }}:{{ tag }}'
    source: pull

- name: Search API - Push image
  community.docker.docker_image:
    name: '{{ ghcr_registry }}/{{ app_name }}:{{ tag }}'
    repository: '{{ quay_registry }}/{{ app_name }}:{{ tag }}'
    push: true
    source: local
