- name: Images tasks
  ansible.builtin.include_tasks:
    file: 'images.yml'
    apply:
      tags: searchapi.images
  tags: searchapi.images

- name: Secrets tasks
  ansible.builtin.include_tasks:
    file: 'secrets.yml'
    apply:
      tags: searchapi.secrets
  tags: searchapi.secrets

- name: Routes tasks
  ansible.builtin.include_tasks:
    file: 'routes.yml'
    apply:
      tags: searchapi.routes
  tags: searchapi.routes

- name: HAProxy tasks
  ansible.builtin.include_tasks:
    file: 'haproxy.yml'
    apply:
      tags: searchapi.haproxy
  tags:
    - searchapi.haproxy
    - searchapi.haproxy.restart

- name: App tasks
  ansible.builtin.include_tasks:
    file: 'app.yml'
    apply:
      tags: searchapi.app
  tags:
    - searchapi.app

- name: Monitoring tasks
  ansible.builtin.include_tasks:
    file: 'monitoring.yml'
    apply:
      tags: searchapi.monitoring
  tags:
    - searchapi.monitoring
