- name: Secrets tasks
  include_tasks:
    file: 'secrets.yml'
    apply:
      tags: Secrets
  tags: Secrets

- name: Image tasks
  include_tasks:
    file: 'image.yml'
    apply:
      tags: image
  tags: image

- name: Route tasks
  include_tasks:
    file: 'route.yml'
    apply:
      tags: route
  tags: route

- name: App tasks
  include_tasks:
    file: 'app.yml'
    apply:
      tags: app
  tags:
    - app
    - app.restart
