- name: SearchAPI - Route
  openshift:
    state: latest
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: '{{ hostname }}'
      namespace: '{{ openshift_namespace }}'
      labels:
        app: '{{ app_name }}'
        team: '{{ team }}'
        epfl.ch/visibility: public
      annotations:
        router.openshift.io/cookie-same-site: Strict
        haproxy.router.openshift.io/hsts_header: max-age=15552001
    spec:
      host: '{{ hostname }}'
      wildcardPolicy: None
      port:
        targetPort: '80'
      tls:
        termination: edge
      to:
        kind: Service
        name: '{{ app_name }}'
        weight: 100
