- name: Search API - Robot pull secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: '{{ app_name }}-pull-secret'
        namespace: '{{ openshift_namespace }}'
      data:
        .dockerconfigjson: '{{ secrets.SEARCH_API_ROBOT_PULL }}'

- name: Search API - Auth Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ app_name }}-auth-secrets'
        namespace: '{{ openshift_namespace }}'
      type: Opaque
      data:
        SEARCH_API_SESSION_SECRET: '{{ secrets.SEARCH_API_SESSION_SECRET | b64encode }}'

- name: Search API - CSE Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ app_name }}-cse-secrets'
        namespace: '{{ openshift_namespace }}'
      type: Opaque
      data:
        SEARCH_API_CSE_API_KEY: '{{ secrets.SEARCH_API_CSE_API_KEY | b64encode }}'

- name: Search API - CadiDB Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ app_name }}-cadidb-secrets'
        namespace: '{{ openshift_namespace }}'
      type: Opaque
      data:
        SEARCH_API_CADIDB_USER: '{{ secrets.SEARCH_API_CADIDB_USER | b64encode }}'
        SEARCH_API_CADIDB_PASSWORD: '{{ secrets.SEARCH_API_CADIDB_PASSWORD | b64encode }}'

- name: Search API - API MD Secrets (api.epfl.ch)
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ app_name }}-md-secrets'
        namespace: '{{ openshift_namespace }}'
      type: Opaque
      data:
        SEARCH_API_MD_USER: '{{ secrets.SEARCH_API_MD_USER | b64encode }}'
        SEARCH_API_MD_PASSWORD: '{{ secrets.SEARCH_API_MD_PASSWORD | b64encode }}'
