- name: SearchAPI - CSE Secrets
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: search-api-cse-secrets
      namespace: '{{ openshift_namespace }}'
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
    _data: |
      SEARCH_API_CSE_API_KEY: "{{ searchapi_secrets.SEARCH_API_CSE_API_KEY | b64encode }}"

- name: SearchAPI - CadiDB Secrets
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: search-api-cadidb-secrets
      namespace: '{{ openshift_namespace }}'
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
    _data: |
      SEARCH_API_CADIDB_USER: "{{ searchapi_secrets.SEARCH_API_CADIDB_USER | b64encode }}"
      SEARCH_API_CADIDB_PASSWORD: "{{ searchapi_secrets.SEARCH_API_CADIDB_PASSWORD | b64encode }}"

- name: SearchAPI - API MD Secrets (api.epfl.ch)
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: search-api-md-secrets
      namespace: '{{ openshift_namespace }}'
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
    _data: |
      SEARCH_API_MD_USER: "{{ searchapi_secrets.SEARCH_API_MD_USER | b64encode }}"
      SEARCH_API_MD_PASSWORD: "{{ searchapi_secrets.SEARCH_API_MD_PASSWORD | b64encode }}"
