all:
  hosts:
    search-dev-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0012d-search-engine
      ansible_python_interpreter: '{{searchapisible_suitcase_dir}}/bin/python3'
  vars:
    hostnames:
      - dev-search-api.epfl.ch
    routes_availability: private
    secrets: '{{ lookup("file", "/keybase/team/epfl_search/api/dev/secrets.yml") | from_yaml }}'
    tag: 0.9.4
