all:
  hosts:
    search-dev-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0012d-search-engine
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars:
    routes_availability: private
    hostnames:
      - dev-search-api.epfl.ch

    haproxy_tag: 3.0.7-alpine
    haproxy_image: 'haproxy:{{ haproxy_tag }}'
    haproxy_config: '{{ lookup("file", "/keybase/team/epfl_search/api/dev/haproxy.cfg") }}'

    secrets: '{{ lookup("file", "/keybase/team/epfl_search/api/dev/secrets.yml") | from_yaml }}'
    tag: 1.1.0
