all:
  hosts:
    search-production-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0012p-search-engine
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
  vars:
    routes_availability: public
    hostnames:
      - search-backend.epfl.ch
      - search-2012.epfl.ch
      - search-api.epfl.ch

    haproxy_tag: 3.0.7-alpine
    haproxy_image: 'haproxy:{{ haproxy_tag }}'
    haproxy_config: '{{ lookup("file", "/keybase/team/epfl_search/api/prod/haproxy.cfg") }}'

    grafana_dashboard_instance: grafana-prod
    grafana_dashboard_api: >-
      {{ lookup("template",
                "/keybase/team/epfl_search/api/prod/grafana-dashboard-api.json") }}

    secrets: '{{ lookup("file", "/keybase/team/epfl_search/api/prod/secrets.yml") | from_yaml }}'
    tag: 2.2.0
