all:
  hosts:
    search-production-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0012p-search-engine
      ansible_python_interpreter: '{{searchapisible_suitcase_dir}}/bin/python3'
  vars:
    hostnames:
      - search-backend.epfl.ch
      - search-2012.epfl.ch
      - search-api.epfl.ch
    routes_availability: public
    secrets: '{{ lookup("file", "/keybase/team/epfl_search/api/prod/secrets.yml") | from_yaml }}'
    tag: 1.0.0
