all:
  children:
    openshift_namespaces:
      hosts:
        wwp: {}
      vars:
        ansible_connection: local
        openshift_namespace: 'wwp'

        hostnames:
          - search-backend.epfl.ch
          - search-2012.epfl.ch
          - search-api.epfl.ch
        tag: latest
        searchapi_secrets: "{{ lookup('file', '/keybase/team/epfl_search/api/prod/secrets.yml') | from_yaml }}"
