all:
  hosts:
    search-staging-openshift:
      ansible_connection: local
      ansible_host: localhost
      openshift_namespace: svc0012t-search-engine
      ansible_python_interpreter: '{{searchapisible_suitcase_dir}}/bin/python3'
  vars:
    routes_availability: private
    hostnames:
      - staging-search-api.epfl.ch

    haproxy_tag: 3.0.7-alpine
    haproxy_image: 'haproxy:{{ haproxy_tag }}'
    haproxy_config: '{{ lookup("file", "/keybase/team/epfl_search/api/staging/haproxy.cfg") }}'

    secrets: '{{ lookup("file", "/keybase/team/epfl_search/api/staging/secrets.yml") | from_yaml }}'
    tag: 1.0.0
