all:
  children:
    openshift_namespaces:
      hosts:
        wwp-test: {}
      vars:
        ansible_connection: local
        openshift_namespace: 'wwp-test'

        hostnames:
          - staging-search-backend.epfl.ch
          - test-search-2012.epfl.ch
          - test-search-api.epfl.ch
        tag: latest
        searchapi_secrets: "{{ lookup('file', '/keybase/team/epfl_search/api/staging/secrets.yml') | from_yaml }}"
