name: Build

on:
  workflow_run:
    workflows:
      - 'Test'
    types:
      - completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . \
            --no-cache \
            --file docker/Dockerfile \
            --tag search-api
