name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test:coverage

      - name: Coverage to Codecov
        uses: codecov/codecov-action@v3
